import 'package:flutter/material.dart';

/// Design tokens extracted from the Stitch "Splash Screen" project.
///
/// All hex values correspond 1-to-1 with the Tailwind config and utility
/// classes generated by Stitch (project 9377871556534040938).
abstract final class AppColors {
  // ──────────────────────────── Brand / Primary ────────────────────────────
  static const Color primary = Color(0xFF135BEC);
  static const Color primaryDark = Color(0xFF0B3FA8);
  static const Color primaryLight = Color(0xFFEEF4FF);
  static const Color primaryContent = Color(0xFFFFFFFF);

  /// Gradient used by primary action buttons.
  static const LinearGradient primaryGradient = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: [Color(0xFF135BEC), Color(0xFF3B82F6)],
  );

  /// Gradient for Splash background (light mode).
  static const LinearGradient splashGradientLight = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: [Color(0xFF135BEC), Color(0xFF0A3A9C)],
  );

  /// Gradient for Splash background (dark mode).
  static const LinearGradient splashGradientDark = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: [Color(0xFF101622), Color(0xFF080B11)],
  );

  // ──────────────────────────── Backgrounds ────────────────────────────────
  static const Color backgroundLight = Color(0xFFF6F6F8);
  static const Color backgroundDark = Color(0xFF101622);

  // ──────────────────────────── Surfaces ───────────────────────────────────
  static const Color surfaceLight = Color(0xFFFFFFFF);
  static const Color surfaceDark = Color(0xFF1C1F27);

  // ──────────────────────────── Text ───────────────────────────────────────
  static const Color textMainLight = Color(0xFF0F172A);
  static const Color textMainDark = Color(0xFFF8FAFC);
  static const Color textSubLight = Color(0xFF64748B);
  static const Color textSubDark = Color(0xFF94A3B8);

  // ──────────────────────────── Borders ────────────────────────────────────
  static const Color borderLight = Color(0xFFE2E8F0);
  static const Color borderDark = Color(0xFF282E39);

  // ──────────────────────────── Semantic accents ───────────────────────────
  static const Color success = Color(0xFF22C55E); // green-500
  static const Color warning = Color(0xFFEAB308); // yellow-500
  static const Color error = Color(0xFFEF4444); // red-500
  static const Color info = Color(0xFF3B82F6); // blue-500
  static const Color accent = Color(0xFFA855F7); // purple-500

  /// Bus icon gold colour used on the splash screen.
  static const Color busGold = Color(0xFFFFD700);

  // ──────────────────────────── Helpers ────────────────────────────────────

  /// Convenience access — avoids repeating `Brightness` checks.
  static Color background(Brightness brightness) =>
      brightness == Brightness.light ? backgroundLight : backgroundDark;

  static Color surface(Brightness brightness) =>
      brightness == Brightness.light ? surfaceLight : surfaceDark;

  static Color textMain(Brightness brightness) =>
      brightness == Brightness.light ? textMainLight : textMainDark;

  static Color textSub(Brightness brightness) =>
      brightness == Brightness.light ? textSubLight : textSubDark;

  static Color border(Brightness brightness) =>
      brightness == Brightness.light ? borderLight : borderDark;

  // ──────────────────────────── Material 3 ColorSchemes ────────────────────

  static ColorScheme get lightScheme => ColorScheme.fromSeed(
        seedColor: primary,
        brightness: Brightness.light,
      ).copyWith(
        primary: primary,
        onPrimary: primaryContent,
        primaryContainer: primaryLight,
        onPrimaryContainer: primaryDark,
        surface: surfaceLight,
        onSurface: textMainLight,
        onSurfaceVariant: textSubLight,
        outline: borderLight,
        outlineVariant: borderLight.withValues(alpha: 0.5),
        error: error,
        tertiary: accent,
        secondary: info,
      );

  static ColorScheme get darkScheme => ColorScheme.fromSeed(
        seedColor: primary,
        brightness: Brightness.dark,
      ).copyWith(
        primary: primary,
        onPrimary: primaryContent,
        primaryContainer: primaryDark,
        onPrimaryContainer: primaryLight,
        surface: surfaceDark,
        onSurface: textMainDark,
        onSurfaceVariant: textSubDark,
        outline: borderDark,
        outlineVariant: borderDark.withValues(alpha: 0.5),
        error: error,
        tertiary: accent,
        secondary: info,
      );
}
